# Generated by Django 4.2.5 on 2023-09-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('straße', models.CharField(max_length=64)),
                ('hausnummer', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sportart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stadt',
            fields=[
                ('plz', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ort', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=64)),
                ('nachname', models.CharField(max_length=8)),
                ('geburtsdatum', models.DateField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='trainiert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.sportart')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='sportart',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.trainer'),
        ),
        migrations.CreateModel(
            name='Mitglied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=64)),
                ('nachname', models.CharField(max_length=8)),
                ('geburtsdatum', models.DateField()),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.adresse')),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='plz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Test.stadt'),
        ),
    ]
