# Generated by Django 4.2.5 on 2023-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedate',
            name='day_code',
        ),
        migrations.AddField(
            model_name='coursedate',
            name='days',
            field=models.TextField(blank=True, null=True),
        ),
    ]
