# Generated by Django 4.2.5 on 2023-09-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coaches',
            new_name='Coaching',
        ),
    ]
