# Generated by Django 4.2.5 on 2023-09-22 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_remove_coursedate_day_code_coursedate_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date', to='Test.coursedate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='Test.sport'),
        ),
        migrations.AlterField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursedate',
            name='days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='m_city', to='Test.city'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='Test.course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='Test.member'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='t_city', to='Test.city'),
        ),
    ]
