# Generated by Django 4.2.5 on 2023-09-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_course_date_alter_course_sport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
