# Generated by Django 4.2.5 on 2023-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_remove_member_first_name_remove_member_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='Max', max_length=64),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='Mustermann', max_length=64),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
