# Generated by Django 4.2.5 on 2023-09-28 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0005_member_first_name_member_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='id_course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='id_member',
            new_name='member',
        ),
    ]
